# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 3552db7053c5266015b008f397b2e7f70d46485041b9bf289ed003ab3d7408350eb9218dbf4000cb059f0ebce27b7d96822499d2276cab3731a1696f2bfea9fa

test:
  secret_key_base: 8d8fca8e908b9c8448c378a4be62e2958f428e8c8da09b18fe4c66ea3af59d883ce69c58970a54b12ce19454a2d8d76d781d518f5e30695c69802571886df45e

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
